project:
  type: website
  output-dir: docs

website:
  title: "dataVizR3"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: house
      - href: apresentacao.qmd
        icon: file-slides
        text: apresentação
      - href: Likert5.qmd
        icon: file-text
        text: Pesquisa Likert
    right:
      - href: https://github.com/nextmarte/dataVizR3
        icon: github
        text: GitHub

format:
  html:
    theme:
      light: flatly
      dark: darkly

css: styles.css



